# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fde2a3006feb3426ed9d7ca409b2fabeb2e61c3d0cd9206859fad42f5d49f4327368080702d54be79a436c18815a28dc0304b7ffaab3ccc00f93c2284d518fd

test:
  secret_key_base: 59c0fcc028402b6b769ebb5e6d7058cae865c1150633a15e93f1aaea5f46bc6548a0d4f317f696a2afeef77845a704525a95a8f22ea3b98c241790fca483f034

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 59c0fcc028402b6b769ebb5e6d7058cae865c1150633a15e93f1aaea5f46bc6548a0d4f317f696a2afeef77845a704525a95a8f22ea3b98c241790fca483f034
